/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include <dust/version.h>
/* Header for class be_uantwerpen_idlab_dust_core_Version_Native */

#ifndef _Included_be_uantwerpen_idlab_dust_core_Version_Native
#define _Included_be_uantwerpen_idlab_dust_core_Version_Native
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     be_uantwerpen_idlab_dust_core_Version_Native
 * Method:    constructor
 * Signature: (I)J
 */
  JNIEXPORT jlong JNICALL Java_be_uantwerpen_idlab_dust_core_Version_00024Native_constructor__I(JNIEnv *, jclass, jint);

  /*
 * Class:     be_uantwerpen_idlab_dust_core_Version_Native
 * Method:    constructor
 * Signature: (II)J
 */
  JNIEXPORT jlong JNICALL Java_be_uantwerpen_idlab_dust_core_Version_00024Native_constructor__II(JNIEnv *, jclass, jint, jint);

  /*
 * Class:     be_uantwerpen_idlab_dust_core_Version_Native
 * Method:    constructor
 * Signature: (III)J
 */
  JNIEXPORT jlong JNICALL Java_be_uantwerpen_idlab_dust_core_Version_00024Native_constructor__III(JNIEnv *, jclass, jint, jint, jint);

  /*
 * Class:     be_uantwerpen_idlab_dust_core_Version_Native
 * Method:    getDustVersion
 * Signature: ()J
 */
  JNIEXPORT jlong JNICALL Java_be_uantwerpen_idlab_dust_core_Version_00024Native_getDustVersion(JNIEnv *, jclass);

  /*
 * Class:     be_uantwerpen_idlab_dust_core_Version_Native
 * Method:    destructor
 * Signature: (J)V
 */
  JNIEXPORT void JNICALL Java_be_uantwerpen_idlab_dust_core_Version_00024Native_destructor(JNIEnv *, jclass, jlong);

  /*
 * Class:     be_uantwerpen_idlab_dust_core_Version_Native
 * Method:    getMajor
 * Signature: ()I
 */
  JNIEXPORT jint JNICALL Java_be_uantwerpen_idlab_dust_core_Version_00024Native_getMajor(JNIEnv *, jclass, jlong pointer);

  /*
 * Class:     be_uantwerpen_idlab_dust_core_Version_Native
 * Method:    hasMajor
 * Signature: ()Z
 */
  JNIEXPORT jboolean JNICALL Java_be_uantwerpen_idlab_dust_core_Version_00024Native_hasMajor(JNIEnv *, jclass, jlong pointer);

  /*
 * Class:     be_uantwerpen_idlab_dust_core_Version_Native
 * Method:    getMinor
 * Signature: ()I
 */
  JNIEXPORT jint JNICALL Java_be_uantwerpen_idlab_dust_core_Version_00024Native_getMinor(JNIEnv *, jclass, jlong pointer);

  /*
 * Class:     be_uantwerpen_idlab_dust_core_Version_Native
 * Method:    hasMinor
 * Signature: ()Z
 */
  JNIEXPORT jboolean JNICALL Java_be_uantwerpen_idlab_dust_core_Version_00024Native_hasMinor(JNIEnv *, jclass, jlong pointer);

  /*
 * Class:     be_uantwerpen_idlab_dust_core_Version_Native
 * Method:    getPatch
 * Signature: ()I
 */
  JNIEXPORT jint JNICALL Java_be_uantwerpen_idlab_dust_core_Version_00024Native_getPatch(JNIEnv *, jclass, jlong pointer);

  /*
 * Class:     be_uantwerpen_idlab_dust_core_Version_Native
 * Method:    hasPatch
 * Signature: ()Z
 */
  JNIEXPORT jboolean JNICALL Java_be_uantwerpen_idlab_dust_core_Version_00024Native_hasPatch(JNIEnv *, jclass, jlong pointer);

  /*
 * Class:     be_uantwerpen_idlab_dust_core_Version_Native
 * Method:    getVersionString
 * Signature: ()Ljava/lang/String;
 */
  JNIEXPORT jstring JNICALL Java_be_uantwerpen_idlab_dust_core_Version_00024Native_getVersionString(JNIEnv *, jclass, jlong pointer);

#ifdef __cplusplus
}
#endif
#endif
